<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
	  <None Remove="Systems\en-US.hjson" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Items\Accessories\" />
	  <Folder Include="Items\Weapons\Ranged\" />
	  <Folder Include="Projectiles\" />
	</ItemGroup>

</Project>